version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build: ./backend
    command: uvicorn api:app --host 0.0.0.0 --port 5000
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    env_file:
      - .env

  worker:
    build: ./backend
    command: python worker.py
    volumes:
      - ./backend:/app
    depends_on:
      - redis
    env_file:
      - .env