FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN apt-get update && apt-get install -y libpq-dev gcc
RUN apt-get update && apt-get install -y \
  chromium \
  chromium-driver
RUN pip install --no-cache-dir -r requirements.txt

COPY . .